export function zshInitScript(): string {
  return [
    "# zoxide-doctor zsh integration",
    "#",
    "# Source this after zoxide has initialized its z function.",
    "",
    "if ! typeset -f z >/dev/null 2>&1; then",
    '  echo "zdr: zoxide function \'z\' is not defined; run zoxide init before zdr init" >&2',
    "else",
    "  if ! typeset -f __zdr_original_z >/dev/null 2>&1; then",
    "    functions[__zdr_original_z]=$functions[z]",
    "  fi",
    "",
    "  z() {",
    '    local __zdr_attempt="zsh-${$}-${EPOCHREALTIME}-${RANDOM}"',
    '    __zdr_attempt="${__zdr_attempt//[^A-Za-z0-9_.-]/_}"',
    '    local __zdr_before="$PWD"',
    '    command zdr record-z --attempt "$__zdr_attempt" --before "$__zdr_before" --shell zsh -- "$@"',
    '    __zdr_original_z "$@"',
    "    local __zdr_status=$?",
    '    command zdr finish-z --attempt "$__zdr_attempt" --after "$PWD" --status "$__zdr_status"',
    '    return "$__zdr_status"',
    "  }",
    "fi",
    "",
    "zdr() {",
    "  case \"$1\" in",
    "    init|record-z|finish-z|clear-recovery-retry|debug-state|debug-candidates|debug-select|debug-corrections|debug-config|debug-events|debug-timing|debug-provider-timing|benchmark-provider|benchmark-suite|doctor|config-provider|prune-events|forget|provider-smoke|provider-list|provider-login|provider-logout|provider-auth-status|--*|-*)",
    "      command zdr \"$@\"",
    "      return $?",
    "      ;;",
    "  esac",
    "",
    "  local __zdr_target",
    '  __zdr_target=$(command zdr "$@")',
    "  local __zdr_status=$?",
    '  if [ $__zdr_status -eq 0 ] && [ -n "$__zdr_target" ]; then',
    '    cd -- "$__zdr_target"',
    "    return $?",
    "  fi",
    "  return $__zdr_status",
    "}",
    "",
    "_zdr_is_no_arg_zdr_command() {",
    "  local __zdr_command=$1",
    "  local __zdr_pattern='^[[:space:]]*(command[[:space:]]+)?zdr[[:space:]]*$'",
    "  [[ \"$__zdr_command\" =~ $__zdr_pattern ]]",
    "}",
    "",
    "_zdr_preexec() {",
    '  if _zdr_is_no_arg_zdr_command "$1"; then',
    "    :",
    "  else",
    '      local __zdr_retry="${XDG_STATE_HOME:-$HOME/.local/state}/zdr/recovery_retry.json"',
    '      [[ -e "$__zdr_retry" ]] && rm -f "$__zdr_retry"',
    "  fi",
    "}",
    "",
    'if [[ -z "${preexec_functions[(r)_zdr_preexec]}" ]]; then',
    "  preexec_functions+=(_zdr_preexec)",
    "fi",
  ].join("\n");
}

export function bashInitScript(): string {
  return [
    "# zoxide-doctor bash integration",
    "#",
    "# Source this after zoxide has initialized its z function.",
    "",
    "__zdr_clear_recovery_retry_file() {",
    '  local __zdr_retry="${XDG_STATE_HOME:-$HOME/.local/state}/zdr/recovery_retry.json"',
    '  [ -e "$__zdr_retry" ] && rm -f "$__zdr_retry"',
    "}",
    "",
    "if ! declare -F z >/dev/null 2>&1; then",
    '  echo "zdr: zoxide function \'z\' is not defined; run zoxide init before zdr init" >&2',
    "else",
    "  if ! declare -F __zdr_original_z >/dev/null 2>&1; then",
    "    eval \"$(declare -f z | sed -E '1{s/^z[[:space:]]*\\(\\)/__zdr_original_z()/;s/^function[[:space:]]+z[[:space:]]*\\(\\)/function __zdr_original_z()/;}')\"",
    "  fi",
    "",
    "  z() {",
    '    local __zdr_pid="${BASHPID:-$$}"',
    '    local __zdr_attempt="bash-${__zdr_pid}-${SECONDS}-${RANDOM}"',
    '    __zdr_attempt="${__zdr_attempt//[^A-Za-z0-9_.-]/_}"',
    '    local __zdr_before="$PWD"',
    '    command zdr record-z --attempt "$__zdr_attempt" --before "$__zdr_before" --shell bash -- "$@"',
    '    __zdr_original_z "$@"',
    "    local __zdr_status=$?",
    '    command zdr finish-z --attempt "$__zdr_attempt" --after "$PWD" --status "$__zdr_status"',
    '    return "$__zdr_status"',
    "  }",
    "fi",
    "",
    "zdr() {",
    "  __zdr_inside_zdr=1",
    "  case \"$1\" in",
    "    init|record-z|finish-z|clear-recovery-retry|debug-state|debug-candidates|debug-select|debug-corrections|debug-config|debug-events|debug-timing|debug-provider-timing|benchmark-provider|benchmark-suite|doctor|config-provider|prune-events|forget|provider-smoke|provider-list|provider-login|provider-logout|provider-auth-status|--*|-*)",
    "      command zdr \"$@\"",
    "      local __zdr_status=$?",
    "      __zdr_last_command=\"zdr-other\"",
    "      __zdr_inside_zdr=0",
    "      return $__zdr_status",
    "      ;;",
    "  esac",
    "",
    '  if [ "$#" -gt 0 ]; then',
    "    __zdr_clear_recovery_retry_file",
    "  fi",
    "",
    "  local __zdr_target",
    '  __zdr_target=$(command zdr "$@")',
    "  local __zdr_status=$?",
    '  if [ "$#" -eq 0 ]; then',
    '    __zdr_last_command="zdr"',
    "  else",
    '    __zdr_last_command="zdr-other"',
    "  fi",
    "  __zdr_inside_zdr=0",
    '  if [ $__zdr_status -eq 0 ] && [ -n "$__zdr_target" ]; then',
    '    cd -- "$__zdr_target"',
    "    return $?",
    "  fi",
    "  return $__zdr_status",
    "}",
    "",
    "__zdr_prompt_command() {",
    "  local __zdr_status=$?",
    '  case "${__zdr_last_command:-}" in',
    "    zdr) ;;",
    "    *) __zdr_clear_recovery_retry_file ;;",
    "  esac",
    "  __zdr_last_command=",
    "  return $__zdr_status",
    "}",
    "",
    "if declare -p PROMPT_COMMAND 2>/dev/null | grep -q '^declare -a'; then",
    '  case " ${PROMPT_COMMAND[*]} " in',
    "    *' __zdr_prompt_command '*) ;;",
    "    *) PROMPT_COMMAND=(__zdr_prompt_command \"${PROMPT_COMMAND[@]}\") ;;",
    "  esac",
    "else",
    '  case ";${PROMPT_COMMAND:-};" in',
    "    *';__zdr_prompt_command;'*) ;;",
    "    *) PROMPT_COMMAND=\"__zdr_prompt_command${PROMPT_COMMAND:+;$PROMPT_COMMAND}\" ;;",
    "  esac",
    "fi",
  ].join("\n");
}

export function fishInitScript(): string {
  return [
    "# zoxide-doctor fish integration",
    "#",
    "# Source this after zoxide has initialized its z function.",
    "",
    "function __zdr_clear_recovery_retry_file",
    '    set -l __zdr_retry "$XDG_STATE_HOME/zdr/recovery_retry.json"',
    '    if test -z "$XDG_STATE_HOME"',
    '        set __zdr_retry "$HOME/.local/state/zdr/recovery_retry.json"',
    "    end",
    '    test -e "$__zdr_retry"; and rm -f "$__zdr_retry"',
    "end",
    "",
    "if not functions --query z",
    '    echo "zdr: zoxide function \'z\' is not defined; run zoxide init before zdr init" >&2',
    "else",
    "    if not functions --query __zdr_original_z",
    "        functions --copy z __zdr_original_z",
    "    end",
    "",
    "    function z",
    "        set -l __zdr_attempt fish-$fish_pid-(date +%s%N)-(random)",
    "        set __zdr_attempt (string replace --regex --all '[^A-Za-z0-9_.-]' '_' -- $__zdr_attempt)",
    '        set -l __zdr_before "$PWD"',
    '        command zdr record-z --attempt "$__zdr_attempt" --before "$__zdr_before" --shell fish -- $argv',
    "        __zdr_original_z $argv",
    "        set -l __zdr_status $status",
    '        command zdr finish-z --attempt "$__zdr_attempt" --after "$PWD" --status "$__zdr_status"',
    "        return $__zdr_status",
    "    end",
    "end",
    "",
    "function zdr",
    '    switch "$argv[1]"',
    "        case init record-z finish-z clear-recovery-retry debug-state debug-candidates debug-select debug-corrections debug-config debug-events debug-timing debug-provider-timing benchmark-provider benchmark-suite doctor config-provider prune-events forget provider-smoke provider-list provider-login provider-logout provider-auth-status '--*' '-*'",
    "            command zdr $argv",
    "            return $status",
    "    end",
    "",
    "    if test (count $argv) -gt 0",
    "        __zdr_clear_recovery_retry_file",
    "    end",
    "",
    "    set -l __zdr_target (command zdr $argv)",
    "    set -l __zdr_status $status",
    '    if test $__zdr_status -eq 0 -a -n "$__zdr_target"',
    '        cd -- "$__zdr_target"',
    "        return $status",
    "    end",
    "    return $__zdr_status",
    "end",
    "",
    "function __zdr_is_no_arg_zdr_command",
    "    set -l __zdr_commandline (string trim -- \"$argv[1]\")",
    "    string match --regex --quiet '^(command[[:space:]]+)?zdr$' -- \"$__zdr_commandline\"",
    "end",
    "",
    "function __zdr_preexec --on-event fish_preexec",
    '    set -l __zdr_commandline (string join " " -- $argv)',
    '    if not __zdr_is_no_arg_zdr_command "$__zdr_commandline"',
    "        __zdr_clear_recovery_retry_file",
    "    end",
    "end",
  ].join("\n");
}
